# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 20:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'produto', 'verbose_name_plural': 'produtos'},
        ),
    ]
